name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt
      
      - name: Check format
        run: cargo fmt -- --check

  Linting:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4

       - name: Install libpostal dependencies
         run: |
           sudo apt-get install -y curl build-essential autoconf automake libtool pkg-config
           git clone https://github.com/openvenues/libpostal
           cd libpostal
           ./bootstrap.sh
           ./configure --datadir=/tmp/libpostal
           make -j4
           sudo make install
           sudo ldconfig
         shell: bash

       - name: Install stable toolchain
         uses: actions-rs/toolchain@v1
         with:
           toolchain: stable
           override: true
           components: clippy

       - name: Lint with clippy
         uses: actions-rs/clippy-check@v1
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
